name:                suavemente
version:             0.2.0.0
github:              "isovector/suavemente"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            An applicative functor that seamlessly talks to HTML inputs.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/suavemente#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- blaze-markup
- bytestring
- colour
- containers
- diagrams-core
- diagrams-lib
- diagrams-svg
- interpolatedstring-perl6
- lens
- mtl
- servant
- servant-blaze
- servant-server
- servant-websockets
- stm
- streaming
- svg-builder
- text
- transformers
- warp
- websockets

library:
  source-dirs: src

# executables:
#   suavemente-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - suavemente

